### ISSUE TITLE
1.6 update - skip minigame part broken

### ISSUE THREAD

**Issue by RavinShadow** [eideehi/sdv-easyfishing#1]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Mod version

1.1.2

### Is this a bug caused by this mod alone?

The bug was reproduced with this mod alone

### What happened?

This mod sorta works with the 1.6 update, but I thought I'd let you know that the skip minigame part of it appears to be broken.

### Steps to reproduce the bug

I just went fishing.

### Logs and screenshots

[Eidee Easy Fishing] This mod failed in the Display.MenuChanged event. Technical details:
InvalidCastException: Can't convert the StardewValley.Menus.BobberBar::whichFish field from System.String to System.Int32.
   at StardewModdingAPI.Framework.Reflection.ReflectedField`1.GetValue() in SMAPI\Framework\Reflection\ReflectedField.cs:line 67
   at EideeEasyFishing.ModEntry.OnMenuChanged(Object sender, MenuChangedEventArgs args) in E:\development\workspaces\mods\stardew_valley\eidee-easy-fishing\EideeEasyFishing\ModEntry.cs:line 130
   at StardewModdingAPI.Framework.Events.ManagedEvent`1.Raise(TEventArgs args) in SMAPI\Framework\Events\ManagedEvent.cs:line 101

**Comment by eideehi** [comment]
I have released version 1.2.0, which is compatible with Stardew Valley 1.6 or later.
